# -*- mode: ruby -*-
# vi: set ft=ruby :

defaultbox = 'ubuntu/trusty64'
box = ENV['BOX'] || defaultbox

ENV['ANSIBLE_ROLES_PATH'] = "../../"

Vagrant.configure(2) do |config|

  config.vm.box = box

  config.vm.define "mkiso" do |mkiso_cfg|
    mkiso_cfg.vm.hostname = "mkiso.vagrant"
    mkiso_cfg.vm.network "private_network", type: "dhcp"
    mkiso_cfg.vm.provider :virtualbox do |v|
      v.name = "mkiso"
      # v.gui = true
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "vagrant.yml"
    ansible.sudo = true
    # ansible.tags = ['debug']
    ansible.groups = {
      "vagrant" => ["mkiso"],
    }
    ansible.extra_vars = {
      ansible_ssh_user: 'vagrant',
      hbase_standalone:   true,
    }

  end

end
